on: [push]
  
name: CI

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.6.2
  SQLX_FEATURES: "rustls,postgres"
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432 
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Posgres client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          key: "sqlx-${{ env.SQLX_VERSION }}"
      - name: Install sqlx-cli
        run:
          cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features=${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      - name: Install Nextest
        run: cargo install cargo-nextest
      - name: Migrate DB
        run: SKIP_DOCKER=TRUE ./scripts/init_db.sh
      - name: Run Tests
        run: cargo nextest run

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Enforce Code Format
        run: cargo fmt --check

  linting:
    name: Linting
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432 
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install Posgres client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          key: "sqlx-${{ env.SQLX_VERSION }}"
      - name: Install sqlx-cli
        run:
          cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features=${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      - name: Migrate DB
        run: SKIP_DOCKER=TRUE ./scripts/init_db.sh
      - name: Lint Code
        run: cargo clippy -- -D warnings

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          key: "sqlx-${{ env.SQLX_VERSION }}"
      - name: Install Posgres client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: Install sqlx-cli
        run:
          cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features=${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      - name: Install Nextest
        run: cargo install cargo-nextest
      - name: Install llvm-cov
        run: cargo install cargo-llvm-cov
      - name: Migrate DB
        run: SKIP_DOCKER=TRUE ./scripts/init_db.sh
      - name: Generate Code Coverage
        run: cargo llvm-cov nextest

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
